### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [2]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'I love being myself',
     'I love Machine Learning',
     'I am an AI engineer',
    'I am a Basket player',
     'I am a good developer',
     'understand the meaning of words',
     'Thank you for visiting',]

In [4]:
sent

['I love being myself',
 'I love Machine Learnign',
 'I am an AI engineer',
 'I am a Basket player',
 'I am a good developer',
 'understand the meaning of words',
 'Thank you for visiting']

In [5]:
### Vocabulary size
voc_size=10000

#### One Hot Representation

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[7801, 8050, 3971, 4539], [7801, 8050, 5897, 2240], [7801, 3869, 4912, 8765, 1849], [7801, 3869, 4846, 1120, 1423], [7801, 3869, 4846, 2488, 2705], [623, 3756, 4307, 4484, 7824], [2414, 550, 6289, 4480]]


### Word Embedding Represntation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7801 8050 3971 4539]
 [   0    0    0    0 7801 8050 5897 2240]
 [   0    0    0 7801 3869 4912 8765 1849]
 [   0    0    0 7801 3869 4846 1120 1423]
 [   0    0    0 7801 3869 4846 2488 2705]
 [   0    0    0  623 3756 4307 4484 7824]
 [   0    0    0    0 2414  550 6289 4480]]


In [10]:
dim=10


In [11]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
print(model.predict(embedded_docs))

[[[-0.01929207  0.00494619 -0.04544985 -0.00198675 -0.03076339
    0.04093652 -0.04470203  0.03421709 -0.01381916 -0.04431645]
  [-0.01929207  0.00494619 -0.04544985 -0.00198675 -0.03076339
    0.04093652 -0.04470203  0.03421709 -0.01381916 -0.04431645]
  [-0.01929207  0.00494619 -0.04544985 -0.00198675 -0.03076339
    0.04093652 -0.04470203  0.03421709 -0.01381916 -0.04431645]
  [-0.01929207  0.00494619 -0.04544985 -0.00198675 -0.03076339
    0.04093652 -0.04470203  0.03421709 -0.01381916 -0.04431645]
  [-0.00628885  0.00789777  0.03263855 -0.01579582 -0.03361911
   -0.0450557  -0.01390042  0.02238652 -0.00404543  0.02774997]
  [ 0.01199391 -0.00726436 -0.00894682 -0.03802612  0.00727352
    0.00113855  0.04411173 -0.00123703  0.02098508  0.01750195]
  [-0.01191666  0.00170326  0.00777863 -0.03062594  0.04377714
    0.03757996 -0.03107708  0.02528224  0.03466804 -0.04194372]
  [ 0.03504499  0.03083986  0.0355772   0.04759209 -0.0119961
    0.01722522 -0.01442803 -0.03334764 -0.0087765

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 7801, 8050, 3971, 4539], dtype=int32)

In [15]:
print(model.predict(embedded_docs)[0])

[[-0.01929207  0.00494619 -0.04544985 -0.00198675 -0.03076339  0.04093652
  -0.04470203  0.03421709 -0.01381916 -0.04431645]
 [-0.01929207  0.00494619 -0.04544985 -0.00198675 -0.03076339  0.04093652
  -0.04470203  0.03421709 -0.01381916 -0.04431645]
 [-0.01929207  0.00494619 -0.04544985 -0.00198675 -0.03076339  0.04093652
  -0.04470203  0.03421709 -0.01381916 -0.04431645]
 [-0.01929207  0.00494619 -0.04544985 -0.00198675 -0.03076339  0.04093652
  -0.04470203  0.03421709 -0.01381916 -0.04431645]
 [-0.00628885  0.00789777  0.03263855 -0.01579582 -0.03361911 -0.0450557
  -0.01390042  0.02238652 -0.00404543  0.02774997]
 [ 0.01199391 -0.00726436 -0.00894682 -0.03802612  0.00727352  0.00113855
   0.04411173 -0.00123703  0.02098508  0.01750195]
 [-0.01191666  0.00170326  0.00777863 -0.03062594  0.04377714  0.03757996
  -0.03107708  0.02528224  0.03466804 -0.04194372]
 [ 0.03504499  0.03083986  0.0355772   0.04759209 -0.0119961   0.01722522
  -0.01442803 -0.03334764 -0.00877652  0.0152009 ]]
